par(mfrow=c(2,2))
plot(exdata$datetime, exdata$Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", type = "l")
plot(exdata$datetime, exdata$Voltage, xlab="datetime", ylab="Voltage", type="l")
plot(exdata$datetime, exdata$Sub_metering_1, xlab="", ylab="Energy sub metering", type = "l")
lines(exdata$datetime, exdata$Sub_metering_2, col = "red")
lines(exdata$datetime, exdata$Sub_metering_3, col = "blue")
legend("topright", lwd= c(1,1,1), col=c("black", "red", "blue"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty="n")
plot(exdata$datetime, exdata$Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="l")
dev.copy(png, "plot4.png")
dev.off()
par(mfrow=c(1,1))