library(tidyr)
library(dplyr)
exdata <- read.table("household_power_consumption.txt", header = TRUE, sep=";", stringsAsFactors = FALSE)
exdata <- exdata %>% unite(datetime, Date, Time, sep=" ")
exdata$datetime <- strptime(exdata$datetime, format="%d/%m/%Y %H:%M:%S")
date1 <- as.POSIXlt("2007-02-01 00:00:00")
date2 <- as.POSIXlt("2007-02-02 23:59:59")
exdata <- subset(exdata, datetime >= date1 & datetime <= date2)
cols <- c(2:8)
exdata[,cols] <- apply(exdata[,cols], 2, function(x) as.numeric(as.character(x)))

par(mfrow=c(2,2))
plot(exdata$datetime, exdata$Global_active_power, xlab="", ylab="Global Active Power (kilowatts)", type = "l")
plot(exdata$datetime, exdata$Voltage, xlab="datetime", ylab="Voltage", type="l")
plot(exdata$datetime, exdata$Sub_metering_1, xlab="", ylab="Energy sub metering", type = "l")
lines(exdata$datetime, exdata$Sub_metering_2, col = "red")
lines(exdata$datetime, exdata$Sub_metering_3, col = "blue")
legend("topright", lwd= c(1,1,1), col=c("black", "red", "blue"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty="n")
plot(exdata$datetime, exdata$Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="l")
dev.copy(png, "plot4.png")
dev.off()
par(mfrow=c(1,1))